mkleehammer/pyodbc

src/getdata.cpp

Increase number of loop iterations to fully pull in data from VARCHAR 65000 fields.
The current pyodbc behavior will never pull in more than 1024 + (2048 * 9) = 19456 bytes.

Fixes #22 - Increase number of loop iterations to fully pull in data

---

index.html

The connections.html file seems to be missing

Point to Connection wiki page in the doc

---

README.md

While there is a package setuputils on PyPI, it was last updated in 2013.

Cleaned up typo.

---

src/getdata.cpp

Fix VS2017 compilation

---

src/cursor.cpp
src/cursor.h
src/params.cpp
src/pyodbc.h

Back out the parameter refactoring and do it again.  We should make tests for any problems that were reported so we know we don't reintroduce them.

Revert parameter code

---

tests3/sqlservertests.py

update tests3/sqlservertests.py to also support FreeTDS ODBC

---

tests3/sqlservertests.py

Make it easier to test newer versions of a driver to see if known issues have been fixed.

allow bypassing of test fallback code for known driver issues

---

src/params.cpp

Fix propagation of truncation errors

---

src/connection.cpp
tests3/sqlservertests.py

Add get_output_converter method to Connection object as described in #496

add get_output_converter method (#496)

---

tests2/testutils.py

Informix throws an error when querying missing datatypes

---

tests2/pgtests.py
tests3/pgtests.py

pgtests cleanup (#538)

---

tests2/mysqltests.py
tests3/mysqltests.py

Add string literal test re: #630

 MySQL test adjustments for ANSI driver (#630) 

---

tests2/pgtests.py
tests3/pgtests.py

As with MySQL Connector/ODBC, the PostgreSQL ODBC driver has both "ANSI" and "Unicode" versions. Make sure that at least one of them ("Unicode", in this case) can handle Unicode literals with characters outside of the BMP.

Add emoticon-as-literal tests for PostgreSQL.

---

README.md

Need that to check wheels for Python 3.8

Add badge with a link to PyPI

---

src/cursor.cpp
src/row.cpp

Just some typos that were found by the lintian tool.

Fix two typos in comments

---

src/params.cpp

if fast_executemany is True NullParam was not recognized

handle NullParam like None in ExecuteMulti

---

src/pyodbc.h

Add BYTE declaration missing from iODBC

---

src/pyodbc.pyi

This PR addresses some issues with the pyodbc.pyi file spelled out in #927 .  It also makes some other cosmetic tweaks to the file.  Specifically:
- Add dunder methods (e.g. `__enter__`) to the classes to make them explicit.  Pylance seems to prefer it that way.
- Add defaults to a couple of the parameters for the `connect()` function.  Again, Pylance seems to need them.
- Remove the `_TV` object which seemed like a good idea at the time but actually just confuses matters.
- Other cosmetic changes: re-arranging some of the constants to make them more readable; adding/updating comments.
Hopefully this will make pyodbc.pyi more compatible with Pylance, mypy, and other static typecheckers.  Note, this PR does not address the issue (925) of how pyodbc.pyi is added to the distributed package.

Fixes to pyodbc.pyi for #927

---

src/connection.cpp
tests3/accesstests.py

Add 'closed' property to Connection

---

tests2/sqlservertests.py
tests3/sqlservertests.py

Avoid error when testing with DSN= connection

---

tests3/pgtests.py

Fixes: #1004
Thanks to @bkline for reporting and diagnostics!

Disable setencoding/setdecoding in tests3/pgtests.py

---

tests3/pgtests.py

Fixes: #1003
Thanks once again to @bkline for reporting the issue and tracking down its source.

Adjust test_columns() in tests3/pgtests.py for newer driver versions

---

src/params.cpp

Fix memory leak with decimal parameters
