mkleehammer/pyodbc

src/cursor.cpp
Looking at src/getdata.cpp, it looks like we return a bytearray on python >= 2.6, so shouldn't claim to return a 'buffer' object (2.6 and 2.7) or 'bytes' (3.x).
=> Fix cursor.description for SQL_*BINARY columns

setup.py
* Use short commit hash instead
* Use less fragile way of determining current branch
=> Fix git version when not on a branch

src/pyodbcmodule.cpp
I had issues between Python's locale, pyodbc and the database's locale. It turns out that when querying for NUMERIC values pyodbc asks the database for a text representation instead of an actual ODBC's SQL_C_NUMERIC, and then attempts to parse it. To separate the decimal part it uses the decimal character of whatever Python's locale configuration was set at the moment pyodbc was imported, and it cannot be changed. This is all right, I understand driver support for this datatype is poor.
However, the locale of Python, the database and the system might be all different for whatever reason, causing pyodbc to parse garbage. Some drivers don't even bother localizing their numbers.
The simplest fix I could come up given I don't know anything about C or Python's C API was to add a pair of …
=> Added functions for setting the decimal separator character.

setup.py
This should fix #82
I don't see any build instructions with required dependencies for pyodbc so I'm unable to completely verify the bug is fixed with this commit but I'm able to create the SOURCES.txt file with `python setup.py egg_info` and the offending absolute paths disappear.
=> Change absolute path to relative in setup.py

setup.py
for certain OSX environments, its not possible to use /usr/local as the prefix for brew, and the standard recommended prefix for alternative installs is $HOMEDIR/homebrew
cc @ilovezfs and @cartazio for external feedback on this homebrew lore.
This would help fix up a lot of issues for folks on my team, and possibly other enterprisey python3 users on OSX. 
many thanks!
=> adding homedir brew as a possible path

src/connection.cpp, src/cursor.cpp, src/errors.cpp, src/errors.h, src/getdata.cpp, src/params.cpp, src/pyodbcmodule.cpp
To fix https://github.com/mkleehammer/pyodbc/issues/251 diagnostic messages are retrieved using the Unicode API SQLGetDiagRec**W**. The default is UTF-16LE, as usual for ODBC, but can be configurable when a connection is provided since it is based on connection.unicode_enc.
Due to the amount of duplication I noticed while preparing this fix, in the future it would be good to revisit pyodbc's error handling in general, since a lot of it could be factored out.
=> Retrieve Unicode diagnostic messages

setup.py
This line fixes the ability to install Pyodbc through PIP after building unixODBC from source on OS X El Capitan and beyond. Otherwise PIP fails with "ld: library not found for -lodbc".
=> Add /usr/local/lib to library_dirs linker setting for OS X

src/errors.cpp
Detect more operational error codes so we can raise more specific error classes for these known cases (seen coming from MSSQL — I can't vouch that these offer any improvement for other DBMSs).
=> Add error subclass mappings for more SQLSTATEs

src/connection.cpp
Use UTF-16 encoding corresponding to the machine's native endian
as a default rather than setting 'utf-16le' even on big-endian
machines.
This change thus only affects big-endian platforms and results in
identical object code being generated on little-endian platforms.
As the default is also mentioned in the documentation, it should be
changed there as well once this patch has been merged.
Fixes https://github.com/mkleehammer/pyodbc/issues/253
=> Use native endian for UTF-16

setup.py
some/most odbc implementations on *nix-like systems use `odbc_config`
as a source of compile-time options about the odbc installation
this change will try to use `odbc_config` at compile time to correctly set LDFLAGS and CFLAGS
=> use odbc_config if it's present

src/cursor.cpp, src/cursor.h, src/params.cpp, src/pyodbc.h
These changes combine both the execute()/regular executemany() with the fast executemany() parameter handling code as much as possible, reducing the duplication from before; there has been some minor enhancement too:
- SQLDescribeParam() used to detect server's parameter type
- setinputsizes() can override the type detection and force a specific parameter type
- Data type conversion has been enhanced to expand the range of usable values; for example, a long integer can be inserted into a character column with full precision. This is done by using the SQL type to decide which C type the Python object should be converted to when binding.
- SQL Server extended date/time types can be inserted at full precision
- datetime objects inserted into SQL Server datetimeoffset columns will preserve …
=> Parameter Array Refactoring

src/params.cpp
Fix a small but significant memory leak with fast executemany().
You can merge this one to fix the leak, if you are not ready to accept the parameter array refactoring.
=> Fix memory leak in fast executemany()

src/cursor.cpp
Free the previous results before attempting to execute again on the cursor.
=> Fix invalid cursor state upon executemany()

src/cnxninfo.cpp
If a Unicode connection string is used, hash.update throws an exception about invalid encoding.
=> Fix use of Unicode connection string in Python2

tests2/sqlservertests.py, tests3/sqlservertests.py
`test_drivers` fails on my Linux test VM because I only have one ODBC driver installed ("ODBC Driver 13 for SQL Server"). There is no real need for more than one driver to be installed.
=> test_drivers tweak for sqlservertests

tests2/sqlservertests.py
Allow tests to run on Python 2.6. CentOS/RH6 default Python is 2.6.6.
=> Allow tests to run on Python 2.6

src/cursor.cpp
Prevents the buffer from overflowing (and crashing Python).
From https://docs.microsoft.com/en-us/sql/odbc/reference/syntax/sqlsetstmtattr-function
"SQL_ATTR_NOSCAN (ODBC 1.0) An **SQLULEN** value that indicates whether the driver should scan SQL strings for escape sequences"
=> Use correct size for SQL_ATTR_NOSCAN attribute

src/cursor.cpp, src/params.cpp
Refactored the BindParameters and execute_many method to use the same input size override mechanism via a function.
Extended the override method so that it is implemented as intended by the original author to allow overriding of either size or type.
=> Extend setinputsizes for overriding types as well

src/connection.cpp
In `RaiseErrorFromHandle`, the spelling in the message was "SQLSetConnnectAttr". I changed the spelling to "SQLSetConnectAttr". Note, I have not run this locally. I was just browsing the repo when I noticed, so I thought a PR couldn't hurt. Please disregard if there is some reason for the current spelling.
=> Fix spelling in error message

tests2/informixtests.py, tests2/sqlservertests.py, tests3/informixtests.py, tests3/sqlservertests.py
It is a common misconception that `DRIVER=` names must be enclosed in curly brackets, e.g.,
```
DRIVER={ODBC Driver 17 for SQL Server}
```
In fact
```
DRIVER=ODBC Driver 17 for SQL Server
```
is perfectly legal. These tweaks allow either form to be used in connection strings for tests.
=> tests: remove requirement that driver name be in curly brackets

src/dbspecific.h, src/getdata.cpp
The [DECFLOAT](https://www.ibm.com/developerworks/data/library/techarticle/dm-0801chainani/index.html) type supports both 16 and 34 digits of precision. I tested these by creating the following table in DB2:
```
CREATE TABLE DB2INST1.DECFLOAT_TEST (
COLUMN1 DECFLOAT(34),
COLUMN2 DECFLOAT(16)
);
INSERT INTO DB2INST1.DECFLOAT_TEST VALUES (9.999999999999999999999999999999, 9.999999999999999);
```
I utilized the following test program:
```
import pyodbc
def main():
c = pyodbc.connect('DSN=SAMPLE; UID=db2inst1; PWD=secret')
cursor = c.cursor()
cursor.execute('select column1, column2 from decfloat_test')
row = cursor.fetchone()
print(row)
if __name__ == '__main__':
main()
```
Without this change, I get the following error:
```
Traceback (most recent call last):
File …
```
=> Support for IBM DB2 DECFLOAT type (-360)

src/cursor.cpp
I noticed that the docstrings were mixed up for cursor.fetchall and cursor.fetchmany.
=> fix cursor doc strings for fetchall and fetchmany

src/errors.cpp
In #255, the code was changed to use the native endianness of the
system, but when a connection failure occurs the encoding was still
hard-coded to utf-16-le which causes mojibake on big endian systems.
Instead use ENCSTR_UTF16NE, which will be either utf-16-le or
utf-16-be, depending on the native endian for the system.
Fixes #563
=> Fix UTF-16 conversion issues for connection errors on big endian

tests2/sqldwtests.py, tests3/sqldwtests.py
DW is different enough from regular SQL Server, especially in the area of supported data types and conversions and transaction behaviour, that whoever wants to run pyODBC's SQL Server tests on it would be better to run these instead.
=> Add tests for Azure SQL DW

tests2/accesstests.py
They were not working in Python 2, because ArgumentParser complains about the `%prog` being invalid.
=> Fix Access tests (Python 2)

tests2/sqlservertests.py, tests3/sqlservertests.py
Ensure correct handling of supplementary characters in `N'...'` literals.
=> Add test_emoticons_as_literal to sqlservertests.py

src/cursor.h, src/params.cpp
The size of a long on 64-bit Linux, Unix, and other LP64 platforms
is 64-bit, so passing the address of it and saying it is a 32-bit
integer will result in only the top 4 bytes being read. While this
does work on little endian systems, on big endian systems these bytes
will always be 0 for values < INT_MAX.
Instead, change the type to be an int, which should be 32 bits on
all supported platforms.
=> Bind 32-bit ints correctly on big endian LP64 systems

tests3/mysqltests.py
Tweak test_fast_executemany in tests3/mysqltests.py for Linux.
=> add skip for fast_executemany test on Linux

src/params.cpp, tests2/sqlservertests.py, tests3/sqlservertests.py
This PR attempts to fix #670 .  Currently, conversions from PyLongObject and PyFloatObject type python parameters to C-style values are not checked for success.  This PR addresses that.
When converting integers, an Overflow exception is generated by [PyLong_AsLongLong()](https://docs.python.org/3/c-api/long.html#c.PyLong_AsLongLong) if the integer value is larger than an 8-byte integer can contain.  For floats, no exception is generated by [PyFloat_AsDouble()](https://docs.python.org/3/c-api/float.html#c.PyFloat_AsDouble) for non-numeric float values, but a ProgrammingError is raised by the driver.
It may be better in future to raise DataError exceptions in both cases, but that would require more extensive code changes.
=> Very large integers and non-numeric floats as parameters

README.md
This updates the README text to include the need for a suitable C++ compiler when installing pyodbc, and a reference to the appropriate wiki page as well.  Hopefully this will help people when installing pyodbc for the first time.
=> Add a note about C++ compilers to README.md

setup.py
On the PyPi website, the project description is derived from the "long description" defined in `setup.py`.  In pyodbc's case, the "long description" is currently quite [short](https://pypi.org/project/pyodbc/#description).  This PR changes `setup.py` to use the contents of the README.md file for the "long description" instead.  This will help to provide more information to users, particuarly those wishing to install pyodbc for the first time.
Also, this PR makes another small fix to `setup.py`.  One of the regex strings is not defined as a "raw" string, yet contains the "\d" regex [character combination](https://docs.python.org/3/library/re.html#regular-expression-syntax).  This currently [raises](https://docs.python.org/3/reference/lexical_analysis.html#string-and-bytes-literals) a …
=> Use README.md for the long description in setup.py

tests3/sqlservertests.py
I'm getting an error when running the `tests3\sqlservertests.py` script.  It seems to be because a table is being dropped within a TRY..CATCH block.  Doing so can introduce complications around transaction management.  The error I'm getting is:
```
======================================================================
ERROR: test_columns (__main__.SqlServerTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
File "tests3\sqlservertests.py", line 1612, in test_columns
self.cursor.execute("""\
pyodbc.ProgrammingError: ('42000', '[42000] [Microsoft][SQL Server Native Client 10.0][SQL Server]The current transaction cannot be committed and cannot support operations that write to the log file. Roll back the transaction. (3930) …
```
=> SQL Server test_columns() test failing

tests2/accesstests.py, tests2/dbapitests.py, tests2/exceltests.py, tests2/informixtests.py, tests2/mysqltests.py, tests2/pgtests.py, tests2/sqldwtests.py, tests2/sqlitetests.py, tests2/sqlservertests.py, tests3/accesstests.py, tests3/dbapitests.py, tests3/exceltests.py, tests3/informixtests.py, tests3/mysqltests.py, tests3/pgtests.py, tests3/sqldwtests.py, tests3/sqlitetests.py, tests3/sqlservertests.py
When running the test scripts from the command line, it's useful to be able to tell programmatically if they succeeded or not.  To make this possible, this PR adds a `sys.exit()` call at the end of the `__main__` section of all the database test scripts.  The test scripts now return 0 if all the tests pass, 1 otherwise.
I've used the TestResult [wasSuccessful()](https://docs.python.org/3/library/unittest.html#unittest.TestResult.wasSuccessful) function to determine if the tests passed or not.  Happy to use an alternate function if preferred.
=> Return an exit code from each test script

tests2/accesstests.py, tests2/exceltests.py, tests2/informixtests.py, tests2/mysqltests.py, tests2/sqldwtests.py, tests2/sqlservertests.py, tests3/accesstests.py, tests3/exceltests.py, tests3/informixtests.py, tests3/mysqltests.py, tests3/sqldwtests.py, tests3/sqlservertests.py
The function `print_library_info()` is used in test scripts to output a whole bunch of detailed info about pyodbc and the driver it is using.  For example:
```
python:  2.7.17 (v2.7.17:c2f86d86e6, Oct 19 2019, 20:49:36) [MSC v.1500 32 bit (Intel)]
pyodbc:  4.0.31b17+commit937a61c C:\projects\pyodbc\build\lib.win32-2.7\pyodbc.pyd
odbc:    03.80.0000
driver:  msodbcsql17.dll 17.05.0001
supports ODBC version 03.80
os:      Windows
unicode: Py_Unicode=2 SQLWCHAR=2
Max VARCHAR = 8000
Max WVARCHAR = 4000
Max BINARY = 8000
2012ServerR2 6.3.9600 Multiprocessor Free
```
This is useful for debugging, but when running the unit tests under normal circumstances, it kinda clutters up the output.  This PR changes the relevant code to output this information only if the "verbose" flag is set.  Actually, …
=> Call print_library_info() in the tests only when the verbose flag is set

.gitignore
This PR just adds some more entries to the `.gitignore` file to make it align better with Python/C++ development.  In particular, it adds file extensions used by various IDEs like Visual Studio.
=> Add more entries to .gitignore

src/pyodbcmodule.cpp
Updated buffer array declaration to accommodate extra space for null terminator and therefore allow DSN to utilize all available space of 32 characters without truncation.
Fixes #718
=> Fix DSN truncation in dataSources()

src/cursor.cpp, src/cursor.h, src/errors.cpp, src/errors.h, tests2/pgtests.py, tests2/sqlservertests.py, tests3/pgtests.py, tests3/sqlservertests.py
Here is my attempt to implement a mechanism for retrieving errors, warnings, and PRINT statements from the database in the manner [described](https://www.python.org/dev/peps/pep-0249/#cursor-messages) in PEP-249, i.e. through the use of a "messages" attribute on cursor objects.  This functionality is being tracked in issue #495 .
Currently, it is not possible for pyodbc clients to retrieve any errors, warnings, or other messages that have been generated by the database.  For example, `PRINT 'Start of Proc'` outputs a message, but pyodbc currently ignores it.  These messages are made available by the driver manager as "diagnostic records" through the [SQLGetDiagRec](https://docs.microsoft.com/en-us/sql/odbc/reference/syntax/sqlgetdiagrec-function) function.
PEP-249 …
=> New cursor "messages" attribute to retrieve PRINT statements

setup.py
Looking at the pyodbc [PyPi](https://pypi.org/project/pyodbc/) page, it appears as if pyodbc does not support Python 3.7 and 3.8.  This is not correct.  Also, it doesn't seem unreasonable to drop official Python 3.4 support, after all it's rather old now.
=> Setup.py drop Py34 and add Py37 Py38

src/params.cpp, tests2/sqlservertests.py, tests3/sqlservertests.py
Without this patch, passing a TVP with no rows will crash
the Python interpreter. Solution from v-chojas.
See https://github.com/mkleehammer/pyodbc/issues/772.
Closes #722.
=> Tell the driver to use the default value for an empty TVP

src/getdata.cpp
Causes ODBC timestamps with hour=24 to be resolved to the equivalent datetime with hour=0.
My C is not the best. Please feel free to tear this apart.
Resolves issue #782
=> Resolves issue #782 -- datetimes with hour=24

tests3/pgtests.py
As part of the merge of PR 773, some code in one of the unit tests ended up in a different unit test, causing the Travis CI tests to fail.  This PR fixes that.  The Travis CI tests should now pass.
=> Move Travis unit test code to the correct function

src/cursor.cpp
This PR should fix the segmentation fault described in #858 .  Function GetDiagRecs() should always return an integer otherwise the stack can become corrupted.  Still not sure why this impacted only RedHat and Oracle Linux distributions but it has to be fixed regardless.  I tested this on a RedHat 8.3 instance.
Whilst we're here, add one to the size of the MessageText string for the terminating NULL character.  Also, add more comments.
=> Fix segmentation fault from GetDiagRecs()

src/params.cpp
For some reason, when using MS SQL Server ODBC Driver 17, against MS SQL Server 17, the `DecimalDigits` param info value is `10`, giving negative index in fast_pow10, thus making array access out of bounds.
In most situations, this would give us a garbage value and likely "truncate" the fraction. In my particular case, the garbage value was `0`, raising a division by zero FPE.
This PR is a quick fix, by adding a 10th element in fast_pow10. A more "robust" solution would be to add a "slow" version if `DecimalDigits > 10` as a fallback.
=> Fix timestamp fraction digits conversion for DecimalDigits larger than 10

.github/workflows/ubuntu_build.yml, appveyor.yml, appveyor/compile.cmd, setup.py
Fixes https://github.com/mkleehammer/pyodbc/issues/954.
Python 3.10.0 final is due for release in October:
* https://www.python.org/dev/peps/pep-0619/
The final release candidate is now out and the Python release team has issued a call to action for community members:
> We strongly encourage maintainers of third-party Python projects to prepare their projects for 3.10 compatibilities during this phase. As always, report any issues to the Python bug tracker.
https://discuss.python.org/t/python-3-10-0rc2-is-now-available/10496?u=hugovk
So let's also test and add support for 3.10.
Drops support for EOL Python 3.5.
=> Add support for Python 3.10, drop EOL 3.5

tests3/testutils.py
Replace deprecated `SafeConfigParser` with `ConfigParser`, deprecated since Python 3.2 and potentially being removed in Python 3.11 (due for release October 2022).
* https://bugs.python.org/issue45173
Remove some unused imports from the same file.
=> Replace deprecated SafeConfigParser with ConfigParser

src/pyodbc.pyi
The signature for `pyodbc.connect()` designates the connection string as
required. However, the implementation in `src/pyodbcmodule.cpp`
`mod_connect` permits the string to be absent if there are no positional
arguments, relying instead on only keyword arguments.  The doc string in
`src/pyodbcmodule.cpp` `connect_doc` also confirms the string may be
optionally supplied.
This patch updates the type signature to reflect the implementation and
documentation.
Signed-off-by: Alex Nelson <alexander.nelson@nist.gov>
=> Designate connection string argument type as optional

src/cnxninfo.cpp, src/errors.h, src/params.cpp
PyUnicode_EncodeUTF8 is deprecated, and PyUnicode_EncodeUTF8(PyUnicode_AS_UNICODE(p), ...) is inefficient.
=> Don't use PyUnicode_Encode API

.github/workflows/ubuntu_build.yml, setup.py
Fixes #175
Ref #688
Closes #668
Closes #685
Fixes #441 and pretty much most issues that mention
` sql.h: No such file or directory`
This changes default version for checkout from `4.0.0-unsupported` to PEP 440 compliant `4.0.dev0`, which is needed by wheels. 
Needs PyPI keys for automated uploads.
Following the guide from https://cibuildwheel.readthedocs.io/en/stable/setup/#github-actions
=> Build wheels with cibuildwheels on GitHub Actions

src/pyodbcmodule.cpp, src/row.cpp, tests3/issue998.py
Current versions of Python write a deprecation warning message to `stderr`, which breaks CGI scripts running under web servers which fold `stderr` into `stdout`, and likely breaks other software. This change replaces the deprecated calls with `PyUnicode_New(size, maxchar)`. The accompanying code to populate the new objects has also been rewritten to use the new PyUnicode APIs.
I have included a unit test, but I assume others more familiar with the project will want to decide how to integrate it with the existing tests. I didn't fold the test in with any of the other sets, because the only sets in tests3 which were not DBMS-specific were for tests of the API, and this isn't a fix of API behavior (or rather, it's a fix of internals related to working with the Python APIs). The test fails …
=> Replace deprecated PyUnicode_FromUnicode(NULL, size) calls (#998)

src/getdata.cpp
PostgreSQL ODBC driver returns year -9999 for -infinity dates, so python raises ValueError exception when reading cursor data, because the year field cannot be less than 1. So, I made modifications to bring the value brought by the ODBC driver to python's accepted limits that are years between 1 and 9999. That way the cursor will not raise any exception and pyodbc becomes compatible with infinity dates, just like psycopg2. The big changes seen on removed and added lines are due to autoformat tool in my VSCode, the only part I touched was the switch case part, to add the SQL_TYPE_TIMESTAMP to correct the values to python's limits.
=> Solving issue with infinity dates

.github/workflows/ubuntu_build.yml
It appears that the libodbc.so and libltdl.so libraries are added to the linux build wheels by the "repair" step in Github Actions.  This step adds any libraries it deems necessary to fulfil the "libraries" attribute in setup.py and also renames the linux build wheel files from "linux" to "manylinux".  As far as I can tell, that last rename is not strictly necessary, and can't be separated out, so I'm disabling that entire repair step.
Also, a few other notes:
- now using the latest version of cibuildwheel, 2.8.1
- for now, continue to use Debian-based linux images (rather than the latest AlmaLinux image)
- macos-10.15 will be removed on Aug 30, so update that
- don't build for musllinux, which seems to be problematic
- still not building 32-bit wheels, but we might want to re-visit that …
=> Fix for #1082 libraries in Linux wheels

tests3/accesstests.py, tests3/dbapitests.py, tests3/exceltests.py, tests3/informixtests.py, tests3/mysqltests.py, tests3/pgtests.py, tests3/sparktests.py, tests3/sqldwtests.py, tests3/sqlitetests.py, tests3/sqlservertests.py
The standard library package `optparse` has been [deprecated](https://docs.python.org/3/library/optparse.html) since Python 3.2.  It will be removed in Python 3.12.  Hence, this PR replaces the use of `optparse` with `argparse` (but not in Python 2.7 code).
=> Use argparse instead of optparse

src/params.cpp
=> Fix memory leak with nvarchar(max) and fast_executemany

.github/workflows/ubuntu_build.yml, appveyor.yml, appveyor/build_script.cmd
Now that Appveyor has added Python 3.11 to their Windows image, we can run the unit tests against Python 3.11 on Windows.
Also, a tweak to the CICD pyodbc install commands to not use the soon-to-be-deprecated form ("python setup.py install").
=> Run unit tests for Python 3.11 with Appveyor

.github/workflows/ubuntu_build.yml, .gitignore, appveyor/test_script.cmd, pyproject.toml, setup.py
The wheels generated by `cibuildwheel` in our CI pipeline currently have the wrong pyodbc package version id.s  For example, the file "pyodbc-**4.0.dev0**-cp310-cp310-win_amd64.whl".  "4.0.dev0" is incorrect and should be something like "4.0.35".  The wheels are given the id "4.0.dev0" because `setup.py` is unable to find any tags in the available git repo.  When building pyodbc locally on laptops, `setup.py` usually figures out the version from the git tags in the local repo.  `setup.py` is unable to figure this out in the CI pipeline because Github Actions does not include the tags when it fetches the repo.  It uses a command similar to:
```
/usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin …
```
=> Fix the package versions in the CI-generated wheels

.github/workflows/ubuntu_build.yml, appveyor/install.ps1, appveyor/test_script.cmd
Turns out, the build tests aren't testing against the latest Windows ODBC driver for SQL Server ([version 18](https://learn.microsoft.com/en-us/sql/connect/odbc/download-odbc-driver-for-sql-server?view=sql-server-ver16)).  This PR addresses that.  Also, when testing on Windows, use a more recent version of the version 17 driver.
=> Test with Windows 18 ODBC driver for SQL Server

src/pyodbc.pyi
This PR enhances the existing `pyodbc.pyi` file by:
- adding docstrings to the module functions, classes, class methods, and class properties
- adding missing parameters to various methods that didn't have them before
- making corrections to a few function signatures
- setting class properties correctly with `@property` (specifically r/o or r/w)
The docstrings are in [Google format](https://google.github.io/styleguide/pyguide.html), although I should say I haven't stuck rigidly to that guide.
The docstrings I've added don't attempt to provide a full description for every function.  The behavior of many functions is complex and I believe the Wiki is still the best place to provide comprehensive documentation.  My intention is to enhance the experience for developers by adding more summary …
=> Add docstrings and more to pyodbc.pyi

setup.py
Use `package*` keyword and correct the installation location of `pyodbc.pyi` instead of the deprecated `data_files` keyword usage. This PR is the direct solution of #925.
=> Correct the install location of `pyodbc.pyi`.

src/pyodbc.pyi
Re #1186 , the typing construct `TypeAlias` was introduced in Python 3.10.  This is causing mypy issues with people who are using older versions of Python.  Hence, drop the `TypeAlias` references in `pyodbc.pyi` and just use the raw typing definition for cursor descriptions.  This appears to solve the mypy issue:
```
(pyodbcpyi38) C:\Users\toast>mypy C:\Users\toast\Documents\GitHub\forks\pyodbc\src\pyodbc.pyi
Success: no issues found in 1 source file
```
Note, the `Final` typing references are being kept, despite them being introduced only in Python 3.8.
=> Don't use py3.10 TypeAlias in pyodbc.pyi

.github/workflows/artifacts_build.yml, .github/workflows/ubuntu_build.yml
The MacOS ARM64 distribution files from CIBUILDWHEEL are not working and I don't know why.  I was hoping they would eventually work with newer versions of cibuildwheel, etc. but that doesn't appear to be the case.  Hence, I'd like to remove the MacOS ARM64 distribution builds from Github Actions.
We will have to figure out a different way of generating the MacOS ARM64 distribution files.  (FYI, I personally don't have access to an ARM64 MacOS laptop so my options are limited.)  Meanwhile, users will have to build their pip installations from source, which is what we recommend anyway.
Also, other tidy ups to the Github Action config files.
=> Don't build MacOS ARM64 distributions

appveyor/after_test.cmd, appveyor/build_script.cmd, appveyor/install.cmd
A small change, but we are being [discouraged ](https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html) from calling `setup.py` directly.  Hence, this PR.
Note, the `setup.py build` command in appveyor/build_script.cmd wasn't actually needed so I've removed that.
Here's the deprecation warning in the AppVeyor [output log](https://ci.appveyor.com/project/mkleehammer/pyodbc/builds/47887868/job/8emc4jdyjodbi3aw):
`C:\Python311-x64\Lib\site-packages\setuptools\_distutils\cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.`
=> Don't call setup.py directly in AppVeyor

src/pyodbc.pyi
Looks like a couple of entities are no longer in the pyodbc interface - "ansi" and "UNICODE_SIZE".  This PR removes them.
=> Remove old Python27 stuff from pyodbc.pyi

.github/workflows/ubuntu_build.yml
This is definitely not crucial, but SQL Server 2022 has been out for a while now.  It might be nice to run our tests against it.
=> Add SQL Server 2022 tests to the Ubuntu build

appveyor/install.ps1
Whilst we're jazzing things up, I thought we could update the ODBC drivers used in AppVeyor.
Note, the MySQL 5.8 driver was only needed for Python 2.7 so it can be removed.
=> Update ODBC driver versions on AppVeyor

README.md
This PR adds the AppVeyor badge to README so it can be seen on the front page of GitHub, etc.  Plus a few other tweaks.
=> Add the AppVeyor badge to the front page

.github/workflows/ubuntu_build.yml, appveyor/test_script.cmd
The CICD pipelines were running only the PostgreSQL and MySQL unit tests on Linux, because the tests were not being run using pytest.  This PR fixes that.  Also, strictly speaking, pytest should be run as a module with the `-m` option (i.e. `python -m pytest`) so I made those amendments too.
There is one test that is failing and I don't know why.  Here is the output:
```
__________________________ test_geometry_null_insert __________________________
cursor = <pyodbc.Cursor object at 0x0364EDA0>
@pytest.mark.skipif(sys.platform.startswith('linux'),
reason='SQL Server Linux does not support -151 yet')
def test_geometry_null_insert(cursor: pyodbc.Cursor):
cnxn = connect()
def convert(value):
return value
cnxn.add_output_converter(-151, convert)  # -151 is SQL Server's geometry …
```
=> Run the CICD tests

MANIFEST.in, setup.py
The stub file pyodbc.pyi needs special care when generating the wheel, to ensure it is placed in the "site-packages" directory on install.  The relevant setup.py code was reverted recently, so I have re-reverted it back.  Apparently, we also need to set "include package data" to False now (because it is defaulted to True when using pyproject.toml).
FYI, this code (or at least its equivalent) does not work in pyproject.toml, hence it must remain in setup.py for the time being.
Also, quick fix for MANIFEST.in.
=> Location of pyodbc.pyi on install

src/params.cpp
This commit returns `false` if the first cell in `GetTableInfo` is NULL, and relies on Python's exception handling of the error instead of issuing a segfault.
You can reproduce the segfault by doing the following with pyodbc 5.0.0b.
Create a container running MS SQL 2017.
```bash
podman pull mcr.microsoft.com/mssql/server:2017-latest
```
```bash
podman run -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=StrongPassword2017" -p 1401:1433 \
--name mssql2017 --hostname mssql2017 -d mcr.microsoft.com/mssql/server:2017-latest
```
```bash
podman exec -it mssql2017 "bash"
```
```bash
/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P "StrongPassword2017"
```
To create the test database in sqlcmd, enter each line below and press enter.
```sql
CREATE DATABASE test
GO
QUIT
```
```bash
exit
```
Start a …
=> Fix segfault for empty iterators

src/pyodbcmodule.cpp
Fixes https://github.com/mkleehammer/pyodbc/issues/1277
My cpp is VERY rusty. Let me know if there is a better solution for this.
=> Allow customization of default odbc version

src/connection.cpp
An attempt to fix the segfault issue #1289 .
It looks like the code to handle byte values in the attrs_before parameter was lost in the v5 upgrade.  I've copied the original code back in.  The only difference is I've replaced the call to PyBytes_AS_STRING with the stable ABI compliant call to PyBytes_AsString.
@mkleehammer / @v-chojas / @gordthompson , I haven't been able to properly test this though, so do please check what I've done.
=> Handle bytes in the attrs_before parameter for pyodbc.connect()

src/pyodbc.pyi, src/pyodbcmodule.cpp
Add the pyodbc.odbcversion attribute to pyodbc.pyi, and tweak the newlines in the pyodbc docs for consistency.
=> docs and pyodbc.pyi updates for pyodbc.odbcversion

appveyor.yml
Python 3.12 is now available on AppVeyor Windows images.  Whilst we're adding that to the mix, I thought we might as well update the build we use too.  So this PR uses the Visual Studio 2022 Windows image, instead of 2019.  It also uses SQL Server 2019 instead of 2017, Postgresql 13 instead of 11, and MySQL8.0 instead of 5.7 which is now past its EOL.
You have to start MSSQL 2019 with a "net start" command, and MySQL 8.0 with a "Start-Service" [command](https://github.com/appveyor/ci/issues/3894#issuecomment-1787625858) but hopefully those will be cleaned up by AppVeyor at some point.
=> AppVeyor Python 3.12 and other updates

.github/workflows/artifacts_build.yml, .github/workflows/codeql-analysis.yml, .github/workflows/ubuntu_build.yml, appveyor.yml
Now that GitHub has made an [ARM64 runner](https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/) available - hurrah! - let's use it to create the problematic macOS ARM64 wheels.
In the GitHub Action artifacts script, I have separated out the builds for each platform into discrete jobs.  They are all slightly different and it seems sensible to have a specific job for each platform.
We were getting a bunch of deprecation warnings about old versions of node, so I have updated the versions of actions/setup-python from v4 to v5, actions/upload-artifact from v3 to v4, and github/codeql-action from v2 to v3.  I have also taken the opportunity to pin various actions to specific minor versions so we know exactly what is being run. …
=> Use M1 runner for macOS arm64 wheels

src/cursor.cpp, src/params.cpp
=> Fix memory leak for strings passed to TVP

src/params.cpp
PY_VERSION_HEX is documented at https://docs.python.org/3/c-api/apiabiversion.html , I think I got it right.
=> Adjust for _PyLong_AsByteArray signature change in Python 3.13 (#1344)

src/dbspecific.h, src/getdata.cpp, src/pyodbc.h, tests/sqlserver_test.py
This commit adds support for decoding the SQL Server `sql_variant` data type.
Attempting to read records containing `sql_variant` columns in the current version of `pyodbc` (5.1.0) results in the following exception:
```
pyodbc.ProgrammingError: ('ODBC SQL type -150 is not yet supported.  column-index=0  type=-150', 'HY106')
```
As mentioned in #307, it is not trivial to write a custom output converter for `sql_variant` as the bytes returned by SQL Server give no indication as to the underlying data type of each value.
This commit adds a `GetData_SqlVariant()` method which retrieves the underlying data type [per the Microsoft documentation](https://learn.microsoft.com/en-us/sql/relational-databases/native-client-odbc-results/mapping-data-types-odbc?view=sql-server-ver15) using …
=> Implemented support for the SQL Server sql_variant data type
